name: Test manually trigger GitHub Actions

on:
  repository_dispatch:
    types: registry-update
  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  build:
    name: Run Scheduled thing
    runs-on: ubuntu-latest
    steps:
      - name: Do something based on manual trigger (CURL)
        run: 'echo  "Metadata is: ${{ github.event.client_payload.module_name }}"'
      - name: Run script from repo
        run: 'chmod +x validate_file.sh && ./validate_file.sh ${{ github.event.client_payload.module_name }} ${{ github.event.client_payload.repository_name }}'
      - name: Run git commands
        run: |
          git add .
          git commit -m "Add content in registry from repository: ${{ github.event.client_payload.repository_name }}"
      - name: Final step
        run: |
          echo "Final step -- module name: ${{ github.event.client_payload.module_name }}"
          echo "Final step -- repository name: ${{ github.event.client_payload.repository_name }}"
