name: Test manually trigger GitHub Actions

on:
  repository_dispatch:
    types: registry-update
  # schedule:
    # - cron: '*/5 * * * *'

jobs:
  build:
    name: Run Scheduled thing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Necessary for accessing files in repository
      - name: Do something based on manual trigger (CURL)
        run: 'echo  "Metadata is: ${{ github.event.client_payload.module_name }}'
      - name: Run script from repo
        run: 'python3 validate_request.py ${{ github.event.client_payload.module_name }}"'
        #run: 'chmod +x validate_file.sh && ./validate_file.sh ${{ github.event.client_payload.module_name }} ${{ github.event.client_payload.repository_name }}'
      #- name: Run git commands
      #  run: |
      #    git --config user.name "myname"
      #    git --config user.email "myemail@email.com"
      #    git add .
      #    git commit -m "Add content in registry from repository: ${{ github.event.client_payload.repository_name }}"
      #- name: Final step
      #  run: |
      #    echo "Final step -- module name: ${{ github.event.client_payload.module_name }}"
      #    echo "Final step -- repository name: ${{ github.event.client_payload.repository_name }}"
